name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r fastapi_blog/requirements.txt
          pip install pytest black flake8 mypy bandit
          pip install sqlalchemy[mypy] types-PyJWT

#      - name: Run tests
#        run: pytest

      - name: Lint
        run: |
          black --check .
          flake8 .
          mypy .

      - name: Security scan
        run: |
          bandit -r app/