# name: Rollback

# on:
#   workflow_dispatch:
#     inputs:
#       revision:
#         required: true

# jobs:
#   rollback:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Configure AWS
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
#           aws-region: us-east-1

#       - name: Configure kubeconfig
#         run: |
#           aws eks update-kubeconfig \
#             --name production-eks \
#             --region us-east-1

#       - name: Rollback
#         run: |
#           helm rollback fastapi \
#             ${{ github.event.inputs.revision }} \
#             -n staging